### ISSUE TITLE
How can I insert a local image in the question body?

### ISSUE THREAD

**Issue by renato-lombardo** [thm-projects/arsnova.click-v2#6]
How can I insert a local image in the question body?
I tried to use the standard markdown:
```
![alternative text](/path/to/image.jpg)
```
But it seems to work only with links on the internet such as:
```
![alternative text](http://www.example.com/image.jpg)
```
I also tried to use this syntax without success:
```
![alternative text](file:///path/to/image.jpg)
```
I even tried to insert pure HTML, but again without success.

**Comment by trayhem** [comment]
There is no way to directly insert local images due to the fact that the attendees do not have that image on their local machine.
You'll need to upload the image to a file hoster (eg. Nextcloud, Google Drive, Dropbox, etc.) and use a public accessible link to the image.
